# Black Swan Event Definitions
# These define catastrophic events that can be triggered by stress combinations

[[black_swan]]
id = "vram_ecc_propagation"
name = "VRAM: Snow of Ash"
triggers = [
  { metric = "bandwidth_util", op = ">", value = 0.95, window_ms = 5000 },
  { metric = "gpu_thermal_events", op = ">=", value = 3, window_ms = 3600000 },
  { metric = "corruption_field", op = ">", value = 0.6, window_ms = 60000 }
]
effects = [
  { InsertOp = { pipeline_id = "can_telemetry", where_ = "all_outbound", op = "Crc" } },
  { DebtPowerMult = { mult = 1.08, duration_ms = 604800000 } },
  { FaultBias = { kind = "StickyConfig", weight_mult = 1.5, duration_ms = 86400000 } },
  { RequireRitual = { ritual_id = "ecc_scrub" } }
]
cooldown_ms = 86400000
weight = 1.0
cure = "ecc_scrub"

[[black_swan]]
id = "pcie_link_flap"
name = "PCIe Link Flap"
triggers = [
  { metric = "bandwidth_util", op = ">", value = 0.9, window_ms = 10000 },
  { metric = "power_draw", op = ">", value = 0.95, window_ms = 30000 }
]
effects = [
  { BandwidthTax = { mult = 1.3, duration_ms = 1800000 } },
  { UIIllusion = { metric = "bandwidth_util", delta = -0.1, duration_ms = 300000 } },
  { DebtHeatAdd = { celsius = 10.0, duration_ms = 900000 } }
]
cooldown_ms = 3600000
weight = 1.2
cure = null

[[black_swan]]
id = "clock_skew_bloom"
name = "Clock Skew Bloom"
triggers = [
  { metric = "corruption_field", op = ">", value = 0.7, window_ms = 120000 },
  { metric = "heat_levels", op = ">", value = 0.8, window_ms = 60000 }
]
effects = [
  { FaultBias = { kind = "DataSkew", weight_mult = 2.0, duration_ms = 1800000 } },
  { UIIllusion = { metric = "corruption_field", delta = -0.05, duration_ms = 600000 } },
  { VramLeak = { mb_per_tick = 0.5, duration_ms = 1200000 } }
]
cooldown_ms = 7200000
weight = 0.8
cure = null

[[black_swan]]
id = "packet_monsoon_echo"
name = "Packet Monsoon Echo"
triggers = [
  { metric = "bandwidth_util", op = ">", value = 0.98, window_ms = 2000 },
  { metric = "gpu_thermal_events", op = ">=", value = 5, window_ms = 1800000 }
]
effects = [
  { BranchDualRun = { pipeline_id = "udp_telemetry_ingest", adjudicator = "Crc" } },
  { DebtPowerMult = { mult = 1.15, duration_ms = 3600000 } },
  { BandwidthTax = { mult = 1.2, duration_ms = 1800000 } }
]
cooldown_ms = 10800000
weight = 0.6
cure = null

[[black_swan]]
id = "numa_ghosting"
name = "NUMA Ghosting"
triggers = [
  { metric = "corruption_field", op = ">", value = 0.8, window_ms = 300000 },
  { metric = "vram_frac", op = ">", value = 0.9, window_ms = 120000 }
]
effects = [
  { QuarantinePipeline = { pipeline_id = "can_telemetry", domain = 1 } },
  { FaultBias = { kind = "StickyConfig", weight_mult = 2.5, duration_ms = 3600000 } },
  { UIIllusion = { metric = "vram_frac", delta = -0.15, duration_ms = 900000 } },
  { RequireRitual = { ritual_id = "numa_rebalance" } }
]
cooldown_ms = 14400000
weight = 0.4
cure = "numa_rebalance"

[[black_swan]]
id = "adjudicator_schism"
name = "Adjudicator Schism"
triggers = [
  { metric = "corruption_field", op = ">", value = 0.9, window_ms = 60000 },
  { metric = "gpu_thermal_events", op = ">=", value = 7, window_ms = 2400000 }
]
effects = [
  { ReplaceOp = { pipeline_id = "can_telemetry", from = "Crc", to = "Kalman" } },
  { DebtPowerMult = { mult = 1.25, duration_ms = 7200000 } },
  { FaultBias = { kind = "DataSkew", weight_mult = 3.0, duration_ms = 3600000 } },
  { UIIllusion = { metric = "corruption_field", delta = -0.2, duration_ms = 1800000 } }
]
cooldown_ms = 21600000
weight = 0.2
cure = null