[package]
name = "colony-mod"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
colony-core = { path = "../colony-core" }
